version: "3.9"

services:
  notesapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"   # Maps host port 80 to container port 8080
      - "7274:8081" # Maps host port 7274 to container port 8081
    depends_on:
      - MyDatabase  # Ensures MyDatabase starts before notesapi

  MyDatabase:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: MyDatabase
    ports:
      - "80:1433"  # Map port 1433 on the host to port 1433 in the container
    environment:
      SA_PASSWORD: "YourStrongPassword123"  # Set the SQL Server admin password
      ACCEPT_EULA: "Y"                      # Accept the license agreement
      MYSQL_DATABASE: MyDatabase
    volumes:
      - sqlserver_data:/var/opt/mssql       # Mount a named volume for data persistence
      - ./init.sql:/var/opt/mssql/init.sql  # Mount the SQL initialization script

volumes:
  sqlserver_data:                           # Declare the volume for persistence
